name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential qemu-system-arm gcc-arm-none-eabi

      - name: Build OS
        run: |
          make clean
          make